### ISSUE TITLE
after upgrade to 0.8.9 has error when start xonsh

### ISSUE THREAD

**Issue by eggcaker** [xonsh/xonsh#3008]
After upgrade to 0.8.9, every time launch xonsh got error:
```
TypeError: source_foreign() got an unexpected keyword argument 'spec'
TypeError: source_foreign() got an unexpected keyword argument 'spec'
TypeError: source_foreign() got an unexpected keyword argument 'spec'
```
## xonfig

```
$ xonfig

+------------------+----------------------+
| xonsh            | 0.8.9                |
| Git SHA          | 4135c690             |
| Commit Date      | Jan 31 10:14:50 2019 |
| Python           | 3.7.1                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.4                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

even delete all the content of .xonshrc still has same error, but if launch `xonsh --no-rc`  it's ok without any error.

**Comment by scopatz** [comment]
Thanks @eggcaker - this is an error with how eval aliases are being partially applied.  Fix incoming.

**Comment by Granitosaurus** [comment]
@scopatz could you reference the issue? I'm curious about the cause of this :)

**Comment by scopatz** [comment]
@Granitosaurus I believe it is the fix in #2992 where calling `value()` now passes in all arguments without first checking if it can.

**Comment by scopatz** [comment]
potential fix in #3009

**Comment by melund** [comment]
@eggcaker #3009 was just merged,  feel free to reopen this if the issue persists.

**Comment by jaraco** [comment]
Confirmed - master is working where 0.8.9 fails.

**Comment by Granitosaurus** [comment]
Now I'm having a different error with `source-bash`

    $ source-bash $(ssh-agent)                                                                                           
    xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 15327, in __init__
        proc = spec.run(pipeline_group=pipeline_group)
      File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 21845, in run
        event_name = self._cmd_event_name()
      File "/usr/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 21919, in _cmd_event_name
        return self.alias.__name__
    AttributeError: 'PartialEvalAlias4' object has no attribute '__name__'

on: 

    | xonsh            | 0.8.10.dev31         |
    | Git SHA          | 39e78970             |

**Comment by melund** [comment]
@Granitosaurus This was a regression in master... There is a fix in #3028
