### PR TITLE
Partial Eval Aliases

### LINKED ISSUE #3008: after upgrade to 0.8.9 has error when start xonsh
After upgrade to 0.8.9, every time launch xonsh got error:
```
TypeError: source_foreign() got an unexpected keyword argument 'spec'
TypeError: source_foreign() got an unexpected keyword argument 'spec'
TypeError: source_foreign() got an unexpected keyword argument 'spec'
```
## xonfig

```
$ xonfig

+------------------+----------------------+
| xonsh            | 0.8.9                |
| Git SHA          | 4135c690             |
| Commit Date      | Jan 31 10:14:50 2019 |
| Python           | 3.7.1                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.4                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

even delete all the content of .xonshrc still has same error, but if launch `xonsh --no-rc`  it's ok without any error.

### PR DESCRIPTION
**Pull request by scopatz**
fixes  #3008

### CODE REVIEW

**Comment by scopatz** [comment]
pinging this @xonsh/xore

**Comment by melund** [comment]
Nice. It works for me :)
