### PR TITLE
Fix regression with LC_MESSAGES missing in locale [No news entry needed.]

### PR DESCRIPTION
**Pull request by melund**
This fixes a regression introduced in #3377, 

The fact that LC_MESSAGES could be missing was handled before. 
https://github.com/xonsh/xonsh/pull/3377/files#diff-b08c376dd29024ccd6f9aef90f2ea96fL836-L838

### CODE REVIEW

**Comment by melund** [comment]
Errors seems to be the annoying: ``AttributeError: module 'builtins' has no attribute '__xonsh__'``

**Comment by laloch** [comment]
The CI failures are not related.
Thanks @melund!

**Comment by bobhy** [comment]
This has the effect of defining environment variable LC_MESSAGES on platforms where `locale.LC_MESSAGES` doesn't exist, albeit to an empty string.  I actually prefer the way it was done (by me!) in https://github.com/bobhy/xonsh/blob/fd9e3f2ca921789bd63229a2d77994799a8a6d75/xonsh/environ.py#L1670-L1677.

**Comment by melund** [comment]
Yes. I agree. Sorry I didn't look at your PR more closely. If you want your solution, create a new PR and I will merge it.

**Comment by bobhy** [comment]
Thanks, new PR #3671.
