### ISSUE TITLE
AttributeError: module 'token' has no attribute 'ASYNC'

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#2638]
After upgrading from Python 3.7.0b3 to 3.7.0b4, an attempt to start the shell fails with the following traceback:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/xonsh", line 2, in <module>
    from xonsh.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/main.py", line 17, in <module>
    from xonsh.execer import Execer
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/execer.py", line 13, in <module>
    from xonsh.built_ins import load_builtins, unload_builtins
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/built_ins.py", line 25, in <module>
    from xonsh.inspectors import Inspector
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/inspectors.py", line 21, in <module>
    from xonsh.tokenize import detect_encoding
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xonsh/tokenize.py", line 57, in <module>
    ASYNC = token.ASYNC
AttributeError: module 'token' has no attribute 'ASYNC'
```

**Comment by jaraco** [comment]
Looks like the change was made in python/cpython@4dc3c8ff14572032e63d9938a12813392bcbe982 as part of [bpo-33260](https://bugs.python.org/issue33260).

**Comment by scopatz** [comment]
Weird, Thanks for reporting! I'll look at your PR to see how they changed it.
