### ISSUE TITLE
Can't keyboard interrupt while loop

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#1743]
If you have a while loop with a command, like

```
while True:
    sleep 1
```

you can't interrupt it. Ctrl-c just restarts the loop.

**Comment by asmeurer** [comment]
Even 

```py
while True:
     try:
         sleep 1
     except KeyboardInterrupt:
         break
```

doesn't work. And the only apparent way to exit is to kill xonsh from another terminal.

**Comment by scopatz** [comment]
This seems to be a subproc / job control issue since 

```
scopatz@artemis ~ $ import time
scopatz@artemis ~ $ while True:
`·.,¸,.·*¯`·.,¸,.·*     time.sleep(1)
`·.,¸,.·*¯`·.,¸,.·*     
^Cscopatz@artemis ~   
```

Can be Ctrl+C'd just fine. Thanks for reporting @asmeurer!

**Comment by adqm** [comment]
I'm not sure I would classify this as a bug, nor am I sure there's an easy way to fix it.

The "problem" (I suspect, based on what I've seen in other cases) is that the Ctrl+C is killing the subprocess (`sleep`) and so is never even reaching xonsh (since we give the terminal over to child processes when they start).  Then another `sleep` process starts up almost immediately thereafter, so Ctrl+C again reaches that process instead of xonsh.

I've had some amounts of success getting around this with:
* press and hold Ctrl+C and wait until it happens to catch xonsh in between killing one `sleep` and starting the next
* press Ctrl+\

That said, I'm not sure there is a real right way to "fix" this, unless we run the whole loop in a subshell.

**Comment by scopatz** [comment]
For what is it worth this is fixed on the run subprocess branch.  The fix involves sending SIGINT to the subprocess, and then if this caused the suprocess to exit, PopenThread will call the original handler from Python.  This will cause Python to walk back up the stack until the shell KeyboardInterrupt handling is reached.

**Comment by scopatz** [comment]
Though Crtl+\ also works!

**Comment by gforsyth** [comment]
Closed via #1758

**Comment by asmeurer** [comment]
This is still happening for me in master. It's especially annoying when running a script, because it becomes difficult to kill (you have to spam Ctrl-C until it dies.

**Comment by gforsyth** [comment]
Damn.  Sorry about that!

**Comment by scopatz** [comment]
Ok, something weird is going on here. On master this works fine for me.  On the new perf branch, the behaviour is as described...

**Comment by asmeurer** [comment]
I see it with the `sleep 1` loop. It sometimes works, though, if I hit it at the right time:

```
xonshmaster%=🐚 while True:
...............     sleep 1
...............     echo test
...............
test
test
^Ctest
test
test
^Ctest
test
^Cxonshmaster%=🐚
```

**Comment by asmeurer** [comment]
Same behavior on `perf`. It's easier to get if you replace `sleep 1` with `sleep 3`.

**Comment by scopatz** [comment]
Strange, on perf with `sleep 3` or `sleep 30` +/- the echo afterwords, it always quits on the first Ctrl-C for me.  Something strange is going on here for sure.  Maybe it is not replacing the original SIGINT handle correctly.

**Comment by scopatz** [comment]
Ok I think that #2087 might be able to close this out.

**Comment by scopatz** [comment]
Alright, that has been merged in. @asmeurer do you want to see if it works for you?

**Comment by asmeurer** [comment]
Seems xonsh master has some other issue (probably with my xonshrc)

```
Traceback (most recent call last):
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/main.py", line 294, in main
    return main_xonsh(args)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/main.py", line 317, in main_xonsh
    shell.shell.cmdloop()
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/shell.py", line 144, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/shell.py", line 107, in singleline
    prompt_args['style'] = PygmentsStyle(pyghooks.xonsh_style_proxy(self.styler))
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/pyghooks.py", line 467, in xonsh_style_proxy
    class XonshStyleProxy(Style):
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/pygments/style.py", line 38, in __new__
    for token in ttype.split():
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/style_tools.py", line 16, in __getattr__
    return tuple.__getattribute__(self, val)
AttributeError: '_TokenType' object has no attribute 'split'
```

**Comment by asmeurer** [comment]
Anyway, I think it works. I'll let you know if I have issues with it again.

**Comment by scopatz** [comment]
That looks like it is is a side effect of some of the recent changes @gforsyth has made to the style code. Probably unrelated to this. I'll close this for now. Thanks for checking @asmeurer!

**Comment by Lillecarl** [comment]
I'm still seeing this issue when doing

```
while True:
  sleep 1
```

Works well enough with time.sleep(1) though, but it's not 100% working on my setup (nixos-unstable, 0.13.1) 😄 

ctrl+\ works, but i end up killing the entire xonsh session this way.
