### PR TITLE
--timings crash fix

### PR DESCRIPTION
**Pull request by JakeHedman**
Running `xonsh --timings` would cause the following error:
```
Traceback (most recent call last):
  File "/home/jake/xonsh/xonsh/main.py", line 400, in main
    args = premain(argv)
  File "/home/jake/xonsh/xonsh/main.py", line 310, in premain
    setup_timings(argv)
  File "/home/jake/xonsh/xonsh/timings.py", line 263, in setup_timings
    @events.on_timingprobe
  File "/home/jake/xonsh/xonsh/events.py", line 72, in __call__
    if debug_level():
  File "/home/jake/xonsh/xonsh/events.py", line 25, in debug_level
    if hasattr(builtins.__xonsh__, "env"):
AttributeError: module 'builtins' has no attribute '__xonsh__'
Xonsh encountered an issue during launch
Failback to /bin/sh
```

Fixed by creating `XonshSession` before calling `setup_timings()` in `premain()`. 

The bug was introduced by 5d9e2146772d589cfb2ddfd60a5592c43c279e10 according to `git bisect`, but I was not able to find any github issue about this.

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @JakeHedman -- thanks for putting this in!  I think this looks good (and `--timings` is also crashing on my end).  I can't log in to azure pipelines from work to restart the job but I'll try to kick it later on and see if we can get CI to pass.

Sorry for the delay in getting to this!

**Comment by JakeHedman** [comment]
@gforsyth: Yay, CI passed! :smiley:

(And the commits are still the same after rebase: `git range-diff origin/master..161171a origin/master..5c812fc`)

**Comment by gforsyth** [comment]
Great!  Thanks again @JakeHedman !
