### ISSUE TITLE
xonsh breaks after updating to 0.3.4 with pip

### ISSUE THREAD

**Issue by lucasicf** [xonsh/xonsh#1233]
The reason is prompt_toolkit needs to be `>= 1.0.0` but upgrading xonsh with pip to `0.3.4` won't pull the newest prompt_toolkit as a dependency. If I don't do that manually, xonsh will break on startup.

```
Successfully installed xonsh-0.3.4
➜  ~ xonsh
/usr/lib/python3.4/site-packages/xonsh/shell.py:66: RuntimeWarning: prompt-toolkit version < v1.0.0 is not supported, xonsh may not work as expected. Please update.
  warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.4', 'console_scripts', 'xonsh')()
  File "/usr/lib/python3.4/site-packages/xonsh/main.py", line 236, in main
    args = premain(argv)
  File "/usr/lib/python3.4/site-packages/xonsh/main.py", line 223, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/lib/python3.4/site-packages/xonsh/shell.py", line 67, in __init__
    from xonsh.ptk.shell import PromptToolkitShell as shell_class
  File "/usr/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 23, in <module>
    from xonsh.ptk.shortcuts import Prompter
  File "/usr/lib/python3.4/site-packages/xonsh/ptk/shortcuts.py", line 6, in <module>
    from prompt_toolkit.enums import EditingMode
ImportError: cannot import name 'EditingMode'
```

**Comment by lucasicf** [comment]
If i uninstall prompt-toolkit it works as a charm.
So the problem is prompt-toolkit being installed AND outdated

**Comment by lucasicf** [comment]
So a possible solution is to improve that warning saying that prompt-toolkit is too old AND xonsh won't run with it. And then do not start with prompt-toolkit. What do you think @scopatz @adqm ?

**Comment by scopatz** [comment]
Sounds reasonable.  I though that these warnings were already in xonsh, but apparently they are not soon enough.

**Comment by adqm** [comment]
I think that sounds good.  I like the idea of warning about PTK being too old, but then falling back to readline so that the shell is still (somewhat) usable.  Maybe that is what we were intending to do before?

**Comment by lucasicf** [comment]
good! working on that. should submit the PR by Thursday.

**Comment by scopatz** [comment]
Great thanks @lucasicf!

**Comment by laerus** [comment]
Solved!
